generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-admin
  files:
  - sitecore-adminpassword.txt
- name: sitecore-database
  files:
  - sitecore-databaseusername.txt
  - sitecore-databasepassword.txt
  - sitecore-databaseservername.txt
  - sitecore-database-elastic-pool-name.txt
  - sitecore-master-database-username.txt
  - sitecore-master-database-password.txt
  - sitecore-core-database-username.txt
  - sitecore-core-database-password.txt
  - sitecore-web-database-username.txt
  - sitecore-web-database-password.txt
  - sitecore-forms-database-username.txt
  - sitecore-forms-database-password.txt
- name: sitecore-identitycertificate
  files:
  - sitecore-identitycertificate.txt
  - sitecore-identitycertificatepassword.txt
- name: sitecore-license
  files:
  - sitecore-license.txt
- name: sitecore-identity
  files:
  - sitecore-identitysecret.txt
  - sitecore-identitysecret_mvp.txt
- name: sitecore-telerik
  files:
  - sitecore-telerikencryptionkey.txt
- name: sitecore-solr
  files:
  - sitecore-solr-connection-string.txt
  - sitecore-solr-core-prefix-name.txt
- name: sitecore-redis
  files:
  - sitecore-redis-connection-string.txt
- name: sitecore-protect-media-requests
  files:
  - sitecore-media-request-protection-shared-secret.txt
- name: okta
  files:
  - okta-auth-server-id.txt
  - okta-client-id.txt
  - okta-client-secret.txt
  - okta-development-mode.txt
  - okta-domain.txt
- name: mvp-application-user
  files:
  - application_user_domain.txt
  - application_user_name.txt
  - application_user_password.txt