apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../xm1/init

images:
- name: scr.sitecore.com/sxp/sitecore-xm1-mssql-init
  newName: "{registry}/sitecore-sps-integration-xm1-mssql-init"
  newTag: 10.2-ltsc2019