---
ID: "0848152b-4ac2-43fd-bbd1-abac5621e1ee"
Parent: "e6ccc220-a1aa-4cef-a9fe-c9c3e6442feb"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/MVP Scripts/Application Export
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    [Sitecore.Data.ID]$applicationTemplateId = "{5A6A420C-BE7E-4822-A887-33C83F5E9B0C}"
    [Sitecore.Data.ID]$peopleRepositoryId = '{64F31E3A-2040-4E69-B9A7-6830CBE669D2}'
    [Sitecore.Data.ID]$StepFolderId = '{8BE29760-EAEC-49CA-BE48-C5C68FD887C5}'
    [Sitecore.Data.ID]$CategoriesFolderId = '{E2F6EA22-562B-4D70-A444-F5BBC81C183E}'
    [Sitecore.Data.ID]$EmploymentStatusFolderId = '{965852BA-C78D-4A41-8DD8-D8CAD7032D4F}'
    [Sitecore.Data.ID]$CountriesFolderId = '{D18D6FFE-DEF4-4D7B-AEA0-13F06B9030A3}'
    [Sitecore.Data.ID]$StatesFolderId = '{F15493BC-613D-4496-BE84-263FB737DCBC}'
    
    $steps = Get-ChildItem -Path "master:" -ID $StepFolderId
    $categories = Get-ChildItem -Path "master:" -ID $CategoriesFolderId
    $employmentStatuses = Get-ChildItem -Path "master:" -ID $EmploymentStatusFolderId
    $countries = Get-ChildItem -Path "master:" -ID $CountriesFolderId
    $states = Get-ChildItem -Path "master:" -ID $StatesFolderId
    
    $applications = Get-ChildItem -Path "master:" -ID $peopleRepositoryId -Recurse |
                    Where-Object { $_.TemplateId -eq $applicationTemplateId }
    
    $reportItems = @()
    foreach($application in $applications) {
        $stepName = "Unknown"
        foreach($stepItem in $steps)
        {
            if($stepItem.ID -eq $application.Step) { $stepName = $stepItem.Title }
        }
    
        $categoryName = "Unknown"
        foreach($categoryItem in $categories)
        {
            if($categoryItem.ID -eq $application.Category) { $categoryName = $categoryItem.Name }
        }
    
        $employmentStatus = "Unknown"
        foreach($employmentStatusItem in $employmentStatuses)
        {
            if($employmentStatusItem.ID -eq $application.EmploymentStatus) { $employmentStatus = $employmentStatusItem.Name }
        }
    
        $country = "Unknown"
        foreach($countryItem in $countries)
        {
            if($countryItem.ID -eq $application.Country) { $country = $countryItem.Name }
        }
        
        $state = "Unknown"
        foreach($stateItem in $states)
        {
            if($stateItem.ID -eq $application.State) { $state = $stateItem.Name }
        }
    
        $completed = $application.Completed -eq 1
        $termsAgree = $application.AgreeOnTerms -eq 1
        
        $reportItem = [PSCustomObject]@{
            "FirstName" = $application.FirstName
            "LastName" = $application.LastName
            "PreferredName" = $application.PreferredName
            "Category" = $categoryName
            "Step" = $stepName
            "Completed" = $completed
            "CompanyName" = $application.CompanyName
            "EmploymentStatus" = $employmentStatus
            "Country" = $country
            "State" = $state
            "Mentor" = $application.Mentor
            "Eligibility" = $application.Eligibility
            "Objectives" = $application.Objectives
            "Blog" = $application.Blog
            "SitecoreCommunity" = $application.SitecoreCommunity
            "CustomerCoreProfile" = $application.CustomerCoreProfile
            "StackExchange" = $application.StackExchange
            "GitHub" = $application.GitHub
            "Twitter" = $application.Twitter
            "Other" = $application.Other
            "AgreeOnTerms" = $termsAgree
            "OnlineAcvitity" = $application.OnlineAcvitity
            "OfflineActivity" = $application.OfflineActivity
        }
        $reportItems += $reportItem
    }
    
    $reportItems | Show-ListView
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211110T033749Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bf96220d-d5ec-4495-a0fb-a9c1587d3429"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211110T043513Z
