apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: mssql
        image: mssql
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-databasepassword.txt
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
          - mountPath: /var/opt/mssql
            name: sql
        resources:
          requests:
            memory: 2Gi
            cpu: 200m
          limits:
            memory: 3Gi
            cpu: 700m    
      volumes:
        - name: sql
          emptyDir: {}