apiVersion: v1
kind: Service
metadata:
  name: sps
spec:
  selector:
    app: sps
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sps
  labels:
    app: sps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sps
  template:
    metadata:
      labels:
        app: sps
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-sps
        image: sitecore-sps
        ports:
        - containerPort: 80
        env:
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: sitecore-license.txt
        - name: Database_Server
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-databaseservername.txt
        - name: Master_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-master-database-username.txt
        - name: Master_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-master-database-password.txt
        - name: Core_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-core-database-username.txt
        - name: Core_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-core-database-password.txt
        - name: Web_Database_Username
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-web-database-username.txt
        - name: Web_Database_Password
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-web-database-password.txt
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        - name: SITECORE_Publishing__ConnectionStrings__Core
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Core;User ID=$(Database_Admin_Username);Password=$(Database_Admin_Password);MultipleActiveResultSets=True
        - name: SITECORE_Publishing__ConnectionStrings__Master
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Master;User ID=$(Database_Admin_Username);Password=$(Database_Admin_Password);MultipleActiveResultSets=True
        - name: SITECORE_Publishing__ConnectionStrings__Service
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Master;User ID=$(Database_Admin_Username);Password=$(Database_Admin_Password);MultipleActiveResultSets=True
        - name: SITECORE_Publishing__ConnectionStrings__Web
          value: Data Source=$(Database_Server);Initial Catalog=Sitecore.Web;User ID=$(Database_Admin_Username);Password=$(Database_Admin_Password);MultipleActiveResultSets=True
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10
        resources:
          requests:
            memory: 400Mi
            cpu: 400m
          limits:
            memory: 2Gi
            cpu: 2000m
      imagePullSecrets:
      - name: sitecore-docker-registry