---
ID: "c51665ec-6662-4bef-8a04-be941861bef7"
Parent: "9c1e30a0-8691-4ad4-bef0-e1f446eef8f3"
Template: "9c1e30a0-8691-4ad4-bef0-e1f446eef8f3"
Path: /sitecore/templates/Project/MvpSite/Homepage/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{EF8DD6F4-1BB8-4831-A1A6-DEFA3594051A}"
- ID: "8e50d26e-5046-490d-8d62-113d2821ad38"
  Hint: Logo SVG path
  Value: /images/sitecore.svg
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1AE49D12-8DA1-4FBD-92FF-887B01C02BB5}">
        <r
          id="{00147A0F-476B-4C99-8A10-E6B4FCFCECE0}"
          ph="header-signin"
          uid="{9DD9C0B4-97B5-4F10-B6E8-C30CC5EE32A5}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200513T045748Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "317422ab-aa5a-405a-94a2-a3dd9d668eb3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220303T112904Z
